language: "en"
early_access: false
reviews:
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: true
  path_filters:
    - "!**/.xml"
    - "!**/.json"
  auto_review:
    enabled: false
    drafts: false