services:
  backend:
    build: .
    container_name: autonow-backend
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: autonow-postgres
    environment:
      POSTGRES_DB: autoNow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
