import { StyleSheet } from 'react-native';

export const createStyles = (theme: any) => StyleSheet.create({
    fab: {
        position: 'absolute',
        right: 20,
        bottom: 24,
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: theme.colors.primary,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: theme.colors.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 6,
    },
    modalBackdrop: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.4)',
        justifyContent: 'flex-end',
    },
    sheet: {
        backgroundColor: theme.colors.surface,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        height: '80%',
        paddingHorizontal: 16,
        paddingTop: 12,
        paddingBottom: 16,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingBottom: 8,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.border,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: theme.colors.textPrimary,
    },
    closeButton: {
        padding: 4,
    },
    messages: {
        flex: 1,
        paddingVertical: 12,
    },
    messageBubble: {
        maxWidth: '85%',
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 14,
        marginBottom: 8,
    },
    bubbleAssistant: {
        alignSelf: 'flex-start',
        backgroundColor: theme.colors.background,
    },
    bubbleUser: {
        alignSelf: 'flex-end',
        backgroundColor: theme.colors.primary,
    },
    bubbleTextAssistant: {
        color: theme.colors.textPrimary,
        fontSize: 14,
        lineHeight: 20,
    },
    bubbleTextUser: {
        color: '#FFFFFF',
        fontSize: 14,
        lineHeight: 20,
    },
    typingText: {
        color: theme.colors.textSecondary,
        fontStyle: 'italic',
        fontSize: 13,
        marginLeft: 4,
        marginBottom: 8,
    },
    ctaButton: {
        alignSelf: 'flex-start',
        marginTop: 4,
        marginBottom: 8,
        backgroundColor: theme.colors.primary,
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 8,
    },
    ctaButtonText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '600',
    },
    inputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingTop: 8,
        borderTopWidth: 1,
        borderTopColor: theme.colors.border,
    },
    input: {
        flex: 1,
        backgroundColor: theme.colors.background,
        borderRadius: 20,
        paddingHorizontal: 14,
        paddingVertical: 10,
        color: theme.colors.textPrimary,
        fontSize: 14,
    },
    sendButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: theme.colors.primary,
        alignItems: 'center',
        justifyContent: 'center',
    },
    sendButtonDisabled: {
        opacity: 0.5,
    },
    errorText: {
        color: theme.colors.error,
        fontSize: 13,
        marginVertical: 4,
    },
});
