spring.application.name=autonow

spring.docker.compose.enabled=false

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.sql.init.mode=never

jwt.secret=${JWT_SECRET}
jwt.algorithm=${JWT_ALGORITHM}
jwt.expiration=${JWT_EXPIRATION}

server.port=8080

springdoc.swagger-ui.enabled=false
springdoc.info.title=AutoNow API
springdoc.info.description=API documentation for AutoNow backend services.
springdoc.info.version=v1
springdoc.servers=
